<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Barang</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f9f9f9;
        }

        .header,
        .footer {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 2em;
        }

        .header p {
            margin: 5px 0;
            font-size: 1em;
        }

        .table-container {
            width: 100%;
            overflow-x: auto;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        th,
        td {
            padding: 12px 15px;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
            text-align: left;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer p {
            font-size: 0.9em;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Laporan Barang Keluar</h1>
        <p>Tanggal: {{ $startdate }} Sampai dengan {{ $enddate }} <span id="tanggal"></span></p>
    </div>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Barang</th>
                    <th>Jumlah Keluar</th>
                    <th>Harga Satuan</th>
                    <th>Total Harga</th>
                </tr>
            </thead>
            @foreach ($data as $key => $item)
                <tbody>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $item->stok->namabarang }}</td>
                    <td>{{ $item->qty }}</td>
                    <td>{{ $item->stok->harga }}</td>
                    <td>{{ $item->stok->harga * $item->qty }}</td>

                </tbody>
            @endforeach
            <tr>
                <th style="text-align: center " colspan="4">
                    Total Keseluruhan
                </th>
                <td colspan="">Rp{{ number_format($total) }}</td>
        </table>
    </div>
    <div class="footer">
        <p>&copy; 2024 PT Trika Media Solusindo. All rights reserved.</p>
        <p>Generated by PT Trika Media Solusindo's inventory system.</p>
    </div>


</body>

</html>
